name: Maven CI

on:
  push:
    branches: [ "main","master","feature/" ]
  pull_request:
    branches: [ "main","master","feature/" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # 3. Build project and run unit tests
      - name: Run unit tests
        run: mvn clean test
        continue-on-error: false

      # 4. Run integration tests
      - name: Run integration tests
        run: mvn verify
        continue-on-error: false
